SELECT C_FIRST, C_MIDDLE, C_LAST, C_STREET_1, C_STREET_2,        C_CITY, C_STATE, C_ZIP, C_PHONE, C_CREDIT, C_CREDIT_LIM,        C_DISCOUNT, C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_SINCE   FROM CUSTOMER WHERE C_W_ID = 1    AND C_D_ID < 10    AND C_ID = 400
SELECT COUNT(*)   FROM CUSTOMER WHERE C_W_ID = 1    AND C_D_ID < 10    AND C_ID < 312
SELECT COUNT(*)   FROM CUSTOMER WHERE C_D_ID < 50    AND C_ID < 427
SELECT COUNT(*)   FROM CUSTOMER WHERE C_W_ID = 1    AND C_D_ID < 25    AND C_ID < 431
SELECT COUNT(*)   FROM CUSTOMER WHERE C_W_ID = 2    AND C_D_ID < 78    AND C_ID < 721
SELECT COUNT(*)   FROM CUSTOMER WHERE C_W_ID = 1    AND C_D_ID < 34    AND C_ID < 374
SELECT COUNT(*)   FROM CUSTOMER WHERE C_D_ID < 67    AND C_ID < 723
SELECT COUNT(*)   FROM CUSTOMER WHERE C_W_ID = 1    AND C_D_ID < 12    AND C_ID < 320
SELECT COUNT(*)   FROM CUSTOMER WHERE C_D_ID < 34    AND C_ID < 340
