SELECT O_C_ID FROM OORDER WHERE O_ID = 2119    AND O_D_ID = 8    AND O_W_ID = 1
SELECT C_FIRST, C_MIDDLE, C_LAST, C_STREET_1, C_STREET_2,        C_CITY, C_STATE, C_ZIP, C_PHONE, C_CREDIT, C_CREDIT_LIM,        C_DISCOUNT, C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_SINCE   FROM CUSTOMER WHERE C_W_ID = 1    AND C_D_ID = 9    AND C_ID = 321
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 8    AND NO_W_ID = 1  ORDER BY NO_O_ID ASC  LIMIT 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL   FROM ORDER_LINE WHERE OL_O_ID = 5577    AND OL_D_ID = 7    AND OL_W_ID = 1
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_PRICE > 99.99
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_PRICE >= 99.99 AND I_ID > 8000
SELECT D_STREET_1, D_STREET_2, D_CITY, D_STATE, D_ZIP, D_NAME  FROM DISTRICT WHERE D_W_ID = 1    AND D_ID = 9
SELECT C_DISCOUNT, C_LAST, C_CREDIT  FROM CUSTOMER WHERE C_W_ID = 2    AND C_D_ID = 3    AND C_ID = 1979
SELECT W_STREET_1, W_STREET_2, W_CITY, W_STATE, W_ZIP, W_NAME  FROM WAREHOUSE WHERE W_ID = 2
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 85094    AND S_W_ID = 2 FOR UPDATE
SELECT C_FIRST, C_MIDDLE, C_LAST, C_STREET_1, C_STREET_2,        C_CITY, C_STATE, C_ZIP, C_PHONE, C_CREDIT, C_CREDIT_LIM,        C_DISCOUNT, C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_SINCE   FROM CUSTOMER WHERE C_W_ID = 2    AND C_D_ID = 1    AND C_ID = 2035
SELECT C_FIRST, C_MIDDLE, C_ID, C_STREET_1, C_STREET_2, C_CITY,        C_STATE, C_ZIP, C_PHONE, C_CREDIT, C_CREDIT_LIM, C_DISCOUNT,        C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_SINCE   FROM CUSTOMER WHERE C_W_ID = 2    AND C_D_ID = 3    AND C_LAST = 'ABLEPRESBAR'  ORDER BY C_FIRST
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 78404    AND S_W_ID = 2 FOR UPDATE
SELECT C_FIRST, C_MIDDLE, C_LAST, C_STREET_1, C_STREET_2,        C_CITY, C_STATE, C_ZIP, C_PHONE, C_CREDIT, C_CREDIT_LIM,        C_DISCOUNT, C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_SINCE   FROM CUSTOMER WHERE C_W_ID = 1    AND C_D_ID = 9    AND C_ID = 321
