SELECT O_C_ID FROM OORDER WHERE O_ID = 2119    AND O_D_ID = 8    AND O_W_ID = 1
SELECT C_FIRST, C_MIDDLE, C_LAST, C_STREET_1, C_STREET_2,        C_CITY, C_STATE, C_ZIP, C_PHONE, C_CREDIT, C_CREDIT_LIM,        C_DISCOUNT, C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_SINCE   FROM CUSTOMER WHERE C_W_ID = 1    AND C_D_ID = 9    AND C_ID = 321
SELECT NO_O_ID FROM NEW_ORDER WHERE NO_D_ID = 8    AND NO_W_ID = 1  ORDER BY NO_O_ID ASC  LIMIT 1
SELECT SUM(OL_AMOUNT) AS OL_TOTAL   FROM ORDER_LINE WHERE OL_O_ID = 5577    AND OL_D_ID = 7    AND OL_W_ID = 1
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_PRICE > 99.99
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_PRICE >= 99.99 AND I_ID > 8000
SELECT D_STREET_1, D_STREET_2, D_CITY, D_STATE, D_ZIP, D_NAME  FROM DISTRICT WHERE D_W_ID = 1    AND D_ID = 9
SELECT C_DISCOUNT, C_LAST, C_CREDIT  FROM CUSTOMER WHERE C_W_ID = 2    AND C_D_ID = 3    AND C_ID = 1979
SELECT W_STREET_1, W_STREET_2, W_CITY, W_STATE, W_ZIP, W_NAME  FROM WAREHOUSE WHERE W_ID = 2
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 85094    AND S_W_ID = 2 FOR UPDATE
SELECT C_FIRST, C_MIDDLE, C_LAST, C_STREET_1, C_STREET_2,        C_CITY, C_STATE, C_ZIP, C_PHONE, C_CREDIT, C_CREDIT_LIM,        C_DISCOUNT, C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_SINCE   FROM CUSTOMER WHERE C_W_ID = 2    AND C_D_ID = 1    AND C_ID = 2035
SELECT C_FIRST, C_MIDDLE, C_ID, C_STREET_1, C_STREET_2, C_CITY,        C_STATE, C_ZIP, C_PHONE, C_CREDIT, C_CREDIT_LIM, C_DISCOUNT,        C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_SINCE   FROM CUSTOMER WHERE C_W_ID = 2    AND C_D_ID = 3    AND C_LAST = 'ABLEPRESBAR'  ORDER BY C_FIRST
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 78404    AND S_W_ID = 2 FOR UPDATE
SELECT C_FIRST, C_MIDDLE, C_LAST, C_STREET_1, C_STREET_2,        C_CITY, C_STATE, C_ZIP, C_PHONE, C_CREDIT, C_CREDIT_LIM,        C_DISCOUNT, C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_SINCE   FROM CUSTOMER WHERE C_W_ID = 1    AND C_D_ID = 9    AND C_ID = 321
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 46175    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 46175
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 31062
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 46175    AND S_W_ID = 1 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 31062    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 89317
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 89317    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 88611
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 88611    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 77414
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 77414    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 96807
SELECT C_DISCOUNT, C_LAST, C_CREDIT  FROM CUSTOMER WHERE C_W_ID = 2    AND C_D_ID = 4    AND C_ID = 767
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 96807    AND S_W_ID = 1 FOR UPDATE
SELECT W_TAX   FROM WAREHOUSE WHERE W_ID = 2
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 19175
SELECT D_NEXT_O_ID, D_TAX   FROM DISTRICT WHERE D_W_ID = 2 AND D_ID = 4 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 19175    AND S_W_ID = 1 FOR UPDATE
UPDATE DISTRICT   SET D_NEXT_O_ID = D_NEXT_O_ID + 1  WHERE D_W_ID = 2    AND D_ID = 4
UPDATE STOCK   SET S_QUANTITY = 13 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 89796    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 70 ,        S_YTD = S_YTD + 3,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 20135    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 15 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 69319    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 38 ,        S_YTD = S_YTD + 4,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 97813    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 15 ,        S_YTD = S_YTD + 9,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 5891    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 35 ,        S_YTD = S_YTD + 4,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 91879    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 40 ,        S_YTD = S_YTD + 4,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 10262    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 13 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 89796    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 70 ,        S_YTD = S_YTD + 3,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 20135    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 15 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 69319    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 38 ,        S_YTD = S_YTD + 4,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 97813    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 15 ,        S_YTD = S_YTD + 9,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 5891    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 35 ,        S_YTD = S_YTD + 4,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 91879    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 40 ,        S_YTD = S_YTD + 4,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 10262    AND S_W_ID = 2
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 5891    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 91879
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 91879    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 10262
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 10262    AND S_W_ID = 2 FOR UPDATE
UPDATE STOCK   SET S_QUANTITY = 24 ,        S_YTD = S_YTD + 2,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 47710    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 89 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 42720    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 18 ,        S_YTD = S_YTD + 6,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 40596    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 97 ,        S_YTD = S_YTD + 4,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 11991    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 90 ,        S_YTD = S_YTD + 5,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 11333    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 50 ,        S_YTD = S_YTD + 5,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 31319    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 46 ,        S_YTD = S_YTD + 6,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 40661    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 64 ,        S_YTD = S_YTD + 3,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 20519    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 20 ,        S_YTD = S_YTD + 2,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 71366    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 46 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 43493    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 66 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 36067    AND S_W_ID = 1
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 81601
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 40661
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 81601    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 40661    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 89558
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 20519
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 89558    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 20519    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 88711
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 71366
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 88711    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 71366    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 43661
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 43493
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 43661    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 43493    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 8699
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 36067
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 8699    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 36067    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 96982
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 40596    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 4679
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 11991
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 4679    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 11991    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 57039
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 11333
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 57039    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 11333    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 4291
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 31319
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 4291    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 31319    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 81601
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 40661
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 81601    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 40661    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 89558
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 20519
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 89558    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 20519    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 88711
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 71366
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 88711    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 71366    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 43661
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 43493
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 43661    AND S_W_ID = 2 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 43493    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 8699
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 36067
UPDATE STOCK   SET S_QUANTITY = 71 ,        S_YTD = S_YTD + 7,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 80611    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 71 ,        S_YTD = S_YTD + 3,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 48483    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 18 ,        S_YTD = S_YTD + 1,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 47743    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 79 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 73430    AND S_W_ID = 1
UPDATE STOCK   SET S_QUANTITY = 19 ,        S_YTD = S_YTD + 6,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 73182    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 88 ,        S_YTD = S_YTD + 8,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 96982    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 72 ,        S_YTD = S_YTD + 5,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 24231    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 43 ,        S_YTD = S_YTD + 9,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 52615    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 64 ,        S_YTD = S_YTD + 6,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 17050    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 10 ,        S_YTD = S_YTD + 2,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 40659    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 25 ,        S_YTD = S_YTD + 6,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 14791    AND S_W_ID = 2
SELECT C_DISCOUNT, C_LAST, C_CREDIT  FROM CUSTOMER WHERE C_W_ID = 1    AND C_D_ID = 4    AND C_ID = 1531
SELECT W_TAX   FROM WAREHOUSE WHERE W_ID = 1
SELECT D_NEXT_O_ID, D_TAX   FROM DISTRICT WHERE D_W_ID = 1 AND D_ID = 4 FOR UPDATE
UPDATE DISTRICT   SET D_NEXT_O_ID = D_NEXT_O_ID + 1  WHERE D_W_ID = 1    AND D_ID = 4
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 14791
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 14791    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 40659
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 40659    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 17050
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 17050    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 52615
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 52615    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 17050
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 17050    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 52615
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 52615    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 24231
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 24231    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 96982
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 96982    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 24231
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 24231    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 52615
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 52615    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 17050
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 17050    AND S_W_ID = 2 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 79463
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 79463    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 48787
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 48787    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 23364
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 23364    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 8775
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 8775    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 46789
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 46789    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 80611
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 80611    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 48483
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 48483    AND S_W_ID = 1 FOR UPDATE
SELECT I_PRICE, I_NAME , I_DATA   FROM ITEM WHERE I_ID = 73430
SELECT C_DISCOUNT, C_LAST, C_CREDIT  FROM CUSTOMER WHERE C_W_ID = 2    AND C_D_ID = 8    AND C_ID = 2428
SELECT W_TAX   FROM WAREHOUSE WHERE W_ID = 2
SELECT D_NEXT_O_ID, D_TAX   FROM DISTRICT WHERE D_W_ID = 2 AND D_ID = 8 FOR UPDATE
SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,        S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10  FROM STOCK WHERE S_I_ID = 73430    AND S_W_ID = 1 FOR UPDATE
UPDATE STOCK   SET S_QUANTITY = 67 ,        S_YTD = S_YTD + 4,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 31062    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 47 ,        S_YTD = S_YTD + 2,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 16027    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 71 ,        S_YTD = S_YTD + 8,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 92883    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 24 ,        S_YTD = S_YTD + 3,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 24295    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 66 ,        S_YTD = S_YTD + 3,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 56583    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 96 ,        S_YTD = S_YTD + 8,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 42727    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 44 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 52694    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 77 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 52965    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 66 ,        S_YTD = S_YTD + 6,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 14183    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 42 ,        S_YTD = S_YTD + 9,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 16487    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 84 ,        S_YTD = S_YTD + 2,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 59558    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 96 ,        S_YTD = S_YTD + 2,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 24279    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 13 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 56414    AND S_W_ID = 2
UPDATE STOCK   SET S_QUANTITY = 83 ,        S_YTD = S_YTD + 10,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 63079    AND S_W_ID = 2
SELECT C_DISCOUNT, C_LAST, C_CREDIT  FROM CUSTOMER WHERE C_W_ID = 1    AND C_D_ID = 8    AND C_ID = 2755
UPDATE STOCK   SET S_QUANTITY = 11 ,        S_YTD = S_YTD + 3,        S_ORDER_CNT = S_ORDER_CNT + 1,        S_REMOTE_CNT = S_REMOTE_CNT + 0  WHERE S_I_ID = 4785    AND S_W_ID = 2
SELECT W_TAX   FROM WAREHOUSE WHERE W_ID = 1
